### ISSUE TITLE
DB ERD 작성

### ISSUE THREAD

**Issue by SeungheonShin** [boostcampwm-2022/web23_MoMyeon#4]
설명
DB를 생성하기 위한 ERD를 작성한다.

해야할 것들
- [x] DB ERD 작성

고려사항

추가사항

완료사항
![Image](https://user-images.githubusercontent.com/75475398/201605042-e96fbaaf-1d75-4f1b-933c-f4d8b9adbd09.PNG)

**Comment by yongseok-dev** [comment]
Wiki에 반영했습니다.
