### ISSUE TITLE
mediasoup 배포서버 적용

### ISSUE THREAD

**Issue by Hyodori04** [boostcampwm-2022/web23_MoMyeon#51]
## 설명

mediasoup 예제 코드 배포서버 적용

## 버그 발생과정
1. produce 버튼 클릭시
2. producerTransport connect 까지만 되고 produce가 작동하지 않음

## 올바른 동작 설명
producerTransport produce 까지 작동해야함
## 스크린샷
<img width="338" alt="스크린샷 2022-11-28 오후 1 53 43" src="https://user-images.githubusercontent.com/57362573/204196792-05d2ff35-90cc-48ca-adfe-488d9166cfaa.png">

**Comment by kabosuMy3a** [comment]
상기 문제로 인해 인스턴스 바꿔서 배포하기로 함

**Comment by kabosuMy3a** [comment]
# 해결 설명

구현한 미디어수프 프로그램이 배포서버에서 안돌아가던 문제 해결을 어제 했습니다. 데모를 저희 프로젝트에 이식하니 똑같은 문제가 발생하더라구요.
결국에는 mediasoup-client와 next.js 를 함께 쓰는 과정에서 생긴 문제였는데요. 따로 만든 데모에서는 되고 왜 이식한 프로젝트에서는 안될까 비교해보니 찾을 수 있었습니다. next.js 13.0.3 버전에서 13.0.5 버전으로 옮기니 잘 동작하네요. 다른 버전에서는 동작 안하는 것을 확인 했습니다.
문제는 이게 7일전 안정화 버전이네요. 제가 구현을 늦게 시작해서 nextjs 프로젝트를 늦게 만들었기 때문에 아마 최신버전으로 설치가 된것 같아요. 효석님의 경우에는 13.0.5 안정화 배포 전에 설치를 하신 것 같구요.
결국 아다리도 잘맞고 운이 좋았던 건데.. 아니었으면 구현이 실패하지 않았을까... nextjs 13.0.5 버전 릴리즈를 봤을 때 어떤 패치가 영향을 준 것인 잘 안보이네요. 프레임워크 선택이 정말 중요한 것 같습니다.
nextjs 와 mediasoup 커뮤니티에 어떤게 영향을 준건지 알고 싶어 글을 썼는데 알려줄지는 잘 모르겠네용 https://mediasoup.discourse.group/t/if-you-are-using-mediasoup-client-with-next-js-upgrade-next-13-0-5/4743 (편집됨)
